language: java
jdk:
- openjdk8
deploy:
  provider: releases
  api_key:
    secure: "qvnNtOg/pIMuu6TlORc6EwJAeszbTvGyue5M5qPiQ56RJFaHHmW1yefVh4bIwydt3Ju4LnJXyYBl7i7WTCJDQj70DhH3GmDENiRalhLxAMFtTTk+Hz6WSYu8VVBj1iQ+attnmxmCBFmlCVRtM5YzYRJu+d/Nm9Abbh9fY6kA+Q+ERoiNJ/npc0QO6z1DFrGTaGog7QkN5K4E7PsNNJN0HFlp+lQZqivoCMrK1gjefZlCZcZ8dQRwCsUOQWlQXKXEcjcUgamvruFyRxL7XYXpQ/BGSlebkFvf65m9pZezPDa+AUa3PkadTLrnv5tJ4FToMFcQpHb788k9MreXPGdT9Nrx60NcLC3BuF44mDSbGJGk2ZTryQdNzWM3FPmU+Lq09ELg8hTeCDM8SpXyKevfsodda1z6WCh6+AKPGVzdntXXpz5NLf9zzJVOULsU18oksQi7MEhPgkVYwf+X94rLmWA52+e3yAP8/hj0KzLLBpyUkabQ3envXaZDCKVr3xZ6FHkuRWCJjRErcCyWurX87D7U6oqltt0iQsIpSUF6gYiDTZ+rofU9nLkMH5T9OSMFrpulVp+ruHldR7Cvk2pfo/ALcv4u3JpV+h0R4wE4RuuRYawAa2nA6kJ75jLKLWC7dCV4nOdcFrI0RTBSJmL147nbVeYfQGqZTcC+KRXrZlc="
  file: target/Werewolf-*.jar
  skip_cleanup: true
  on:
    repo: DoggyCraft/Werewolf
    tags: true
sudo: false
before_install:
  - mkdir lib/
  - wget -P "lib/" https://www.doggycraft.dk/lib/MySkin.jar
addons:
  sonarcloud:
    organization: "dogonfire"
    token:
      secure: "TSveGpsVp/WNHcB7zMD8Bool6j09F1J95L6dnWF8slJrUlytZOUMCSP76MdiLngnBaiWlXAkgBnD1QEwdg/xkrl6EVBTT3oys2AKhikR4+CRmgZRoW/adSmOR/GUA6IPM/Uj2iM+bWkjFxAFHvvA0TrNjqmAHEaKpMRL+yHsKysKXapIJ2nd/VEfv4gO9OXt7YbKLGgNgWdhuWlbC10rwhHPO8Bj4yRr3UeILqFUF2C7wHJt+w45Gcd4oG//A7anWcLWR+QUeJx5HVe2sAFPIOVslxnY6eFxcZXOVXsiW2yRehyo/ANEnGEcfAfiKyZ5hqgLWhth7fs6AeolozkWAT4M0S+uu8YyPeNk7HlUwEiMAMxtnB5zv2Q0i9XU1d2d3AYwX/Ru5kaMILp0zmT8SryjEsnEwpNmMdK3KmuUqIjwcdClvZyS6Z7WRvth+rtI5QBzZlYl3L6b9tRN1mVUQFeM5Sgo4sYowPfwMnHyhDAb4zuH2gwwFRtSMbuxesK7GpN2DiXKDx1K0UlXWCt2CviyIjnG1iYHVE6kLvMq0W668l8NrM6ANtj5Q0PoBXgAYI+Im8A/h8Hf5MAiC/J9Ou9KFLndxV+aO26nnTYkrFpPB1lfhncb7fcucsmu+M0Ld37hFQtp+rZ3jSPnhQFFuMRqwx1lMHbsQB1tqfCMWvg="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DogOnFire_Werewolf
